server:
  port: 8761

spring:
  application:
    name: wooden

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://39.106.71.119:8762/merry/,http://39.106.71.119:8763/sunny/
  server:
    enable-self-preservation: false
