server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://39.106.71.119:8762/eureka/,http://39.106.71.119:8763/eureka/
    fetch-registry: true
#  server:
#    enable-self-preservation: false
